language: python
sudo: false
python:
  - "2.7"

install:
  # Do nothing
  - true
 
script:
  # Do nothing
  - true

env:
  global:
  - ENCRYPTION_LABEL: "04bc118c371a"
  - COMMIT_AUTHOR_EMAIL: "storage-dev@chromium.org"

branches:
  only:
  - gh-pages
