language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#travis-ci
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip3 install bikeshed

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "04bc118c371a"
  - COMMIT_AUTHOR_EMAIL: "storage-dev@chromium.org"

branches:
  # Don't do this on the gh-pages branch.
  except:
  - gh-pages
